
name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: debug
        run: |
          sudo cat /etc/apt/sources.list
          
      - name: update podman
        run: |
          sudo apt-get update
          apt-cache madison docker.io
          sudo apt-get install --only-upgrade podman
          podman version
      
      - name: test docker-daemon
        run: |
          echo "Docker Version"
          docker version
          docker pull alpine:latest
          echo
          echo "Podman Version"
          podman version
          podman pull docker-daemon:alpine:latest
